version: '2.1'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'

  rabbit:
    container_name: rabbit
    hostname: rabbit
    image: 'rabbitmq:3-management'
    labels:
      NAME: 'rabbit'
    ports:
      - '15672:15672'
      - '5672:5672'

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'

  nestjs-boilerplate:
    container_name: nestjs-boilerplate
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - rabbit
      - jaeger
    env_file:
      - .env
    ports:
      - 4400:4400
      - 9229:9229
    ## set your startup file here
    command: npm run start:debug
