version: '2.1'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
      
  rabbit:
    container_name: rabbit
    hostname: rabbit
    labels:
      NAME: "rabbit"
    image: "rabbitmq:3-management"
    ports: 
      - "15672:15672"
      - "5672:5672"

  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1234
  #     POSTGRES_DB: nium-dev  # Ensure this matches the PGDATABASE
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  postgres:
  image: postgres:13
  container_name: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: 1234
    POSTGRES_DB: nium-dev
  ports:
    - "5432:5432"
  volumes:
    - postgres-data:/var/lib/postgresql/data
  healthcheck:
    test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nium-dev"]
    interval: 10s
    retries: 5
    start_period: 30s
    timeout: 5s


  nestjs-boilerplate:
    image: nestjs-boilerplate
    container_name: nestjs-boilerplate
    depends_on: 
      - redis
      - rabbit
      - postgres  # Ensure that the NestJS service waits for PostgreSQL
  
    build: .
    env_file:
      - .env
    ports:
      - 4400:4400
    command: npm run start:prod
