version: '2.1'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
      
  rabbit:
    container_name: rabbit
    hostname: rabbit
    labels:
      NAME: "rabbit"
    image: "rabbitmq:3-management"
    ports: 
      - "15672:15672"
      - "5672:5672"

  nestjs-boilerplate:
    image: nestjs-boilerplate
    container_name: nestjs-boilerplate
    depends_on: 
      - redis
      - rabbit
    build: .
    env_file:
      - .env
    ports:
      - 4400:4400
    command: npm run start:prod
